# Tomcat配置
server:
  # 8080经常被占用
  port: 8090
  tomcat:
    basedir: /usr/local/logs
    max-threads: 200
    uri-encoding: utf-8
logging:
  path: logs
  file: logs/fss.log
spring:
  datasource:
    #    必须添加后面的参数，新版驱动就这样
    url: jdbc:mysql://192.168.1.3:3306/fss?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: kuirons
    name: fss
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/static/apphtml,classpath:/public/,file:D:/ffsstatic,file:/usr/local/static/
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: com.wgy.flowershopserver.pojo
# 配置图片上传相关参数
